/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro_generated_types.root_view_entity.property;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Energyurbanismcharacteristic extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4419640799479376030L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Energyurbanismcharacteristic\",\"namespace\":\"avro_generated_types.root_view_entity.property\",\"fields\":[{\"name\":\"freeText\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Freetext\",\"namespace\":\"avro_generated_types.root_view_entity.property.energyurbanismcharacteristic\",\"fields\":[{\"name\":\"fr\",\"type\":[\"null\",\"string\"]},{\"name\":\"nl\",\"type\":[\"null\",\"string\"]},{\"name\":\"en\",\"type\":[\"null\",\"string\"]},{\"name\":\"de\",\"type\":[\"null\",\"string\"]}]}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Energyurbanismcharacteristic> ENCODER =
      new BinaryMessageEncoder<Energyurbanismcharacteristic>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Energyurbanismcharacteristic> DECODER =
      new BinaryMessageDecoder<Energyurbanismcharacteristic>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Energyurbanismcharacteristic> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Energyurbanismcharacteristic> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Energyurbanismcharacteristic>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Energyurbanismcharacteristic to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Energyurbanismcharacteristic from a ByteBuffer. */
  public static Energyurbanismcharacteristic fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public avro_generated_types.root_view_entity.property.energyurbanismcharacteristic.Freetext freeText;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Energyurbanismcharacteristic() {}

  /**
   * All-args constructor.
   * @param freeText The new value for freeText
   */
  public Energyurbanismcharacteristic(avro_generated_types.root_view_entity.property.energyurbanismcharacteristic.Freetext freeText) {
    this.freeText = freeText;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return freeText;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: freeText = (avro_generated_types.root_view_entity.property.energyurbanismcharacteristic.Freetext)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'freeText' field.
   * @return The value of the 'freeText' field.
   */
  public avro_generated_types.root_view_entity.property.energyurbanismcharacteristic.Freetext getFreeText() {
    return freeText;
  }

  /**
   * Sets the value of the 'freeText' field.
   * @param value the value to set.
   */
  public void setFreeText(avro_generated_types.root_view_entity.property.energyurbanismcharacteristic.Freetext value) {
    this.freeText = value;
  }

  /**
   * Creates a new Energyurbanismcharacteristic RecordBuilder.
   * @return A new Energyurbanismcharacteristic RecordBuilder
   */
  public static avro_generated_types.root_view_entity.property.Energyurbanismcharacteristic.Builder newBuilder() {
    return new avro_generated_types.root_view_entity.property.Energyurbanismcharacteristic.Builder();
  }

  /**
   * Creates a new Energyurbanismcharacteristic RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Energyurbanismcharacteristic RecordBuilder
   */
  public static avro_generated_types.root_view_entity.property.Energyurbanismcharacteristic.Builder newBuilder(avro_generated_types.root_view_entity.property.Energyurbanismcharacteristic.Builder other) {
    return new avro_generated_types.root_view_entity.property.Energyurbanismcharacteristic.Builder(other);
  }

  /**
   * Creates a new Energyurbanismcharacteristic RecordBuilder by copying an existing Energyurbanismcharacteristic instance.
   * @param other The existing instance to copy.
   * @return A new Energyurbanismcharacteristic RecordBuilder
   */
  public static avro_generated_types.root_view_entity.property.Energyurbanismcharacteristic.Builder newBuilder(avro_generated_types.root_view_entity.property.Energyurbanismcharacteristic other) {
    return new avro_generated_types.root_view_entity.property.Energyurbanismcharacteristic.Builder(other);
  }

  /**
   * RecordBuilder for Energyurbanismcharacteristic instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Energyurbanismcharacteristic>
    implements org.apache.avro.data.RecordBuilder<Energyurbanismcharacteristic> {

    private avro_generated_types.root_view_entity.property.energyurbanismcharacteristic.Freetext freeText;
    private avro_generated_types.root_view_entity.property.energyurbanismcharacteristic.Freetext.Builder freeTextBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro_generated_types.root_view_entity.property.Energyurbanismcharacteristic.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.freeText)) {
        this.freeText = data().deepCopy(fields()[0].schema(), other.freeText);
        fieldSetFlags()[0] = true;
      }
      if (other.hasFreeTextBuilder()) {
        this.freeTextBuilder = avro_generated_types.root_view_entity.property.energyurbanismcharacteristic.Freetext.newBuilder(other.getFreeTextBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Energyurbanismcharacteristic instance
     * @param other The existing instance to copy.
     */
    private Builder(avro_generated_types.root_view_entity.property.Energyurbanismcharacteristic other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.freeText)) {
        this.freeText = data().deepCopy(fields()[0].schema(), other.freeText);
        fieldSetFlags()[0] = true;
      }
      this.freeTextBuilder = null;
    }

    /**
      * Gets the value of the 'freeText' field.
      * @return The value.
      */
    public avro_generated_types.root_view_entity.property.energyurbanismcharacteristic.Freetext getFreeText() {
      return freeText;
    }

    /**
      * Sets the value of the 'freeText' field.
      * @param value The value of 'freeText'.
      * @return This builder.
      */
    public avro_generated_types.root_view_entity.property.Energyurbanismcharacteristic.Builder setFreeText(avro_generated_types.root_view_entity.property.energyurbanismcharacteristic.Freetext value) {
      validate(fields()[0], value);
      this.freeTextBuilder = null;
      this.freeText = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'freeText' field has been set.
      * @return True if the 'freeText' field has been set, false otherwise.
      */
    public boolean hasFreeText() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'freeText' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public avro_generated_types.root_view_entity.property.energyurbanismcharacteristic.Freetext.Builder getFreeTextBuilder() {
      if (freeTextBuilder == null) {
        if (hasFreeText()) {
          setFreeTextBuilder(avro_generated_types.root_view_entity.property.energyurbanismcharacteristic.Freetext.newBuilder(freeText));
        } else {
          setFreeTextBuilder(avro_generated_types.root_view_entity.property.energyurbanismcharacteristic.Freetext.newBuilder());
        }
      }
      return freeTextBuilder;
    }

    /**
     * Sets the Builder instance for the 'freeText' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public avro_generated_types.root_view_entity.property.Energyurbanismcharacteristic.Builder setFreeTextBuilder(avro_generated_types.root_view_entity.property.energyurbanismcharacteristic.Freetext.Builder value) {
      clearFreeText();
      freeTextBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'freeText' field has an active Builder instance
     * @return True if the 'freeText' field has an active Builder instance
     */
    public boolean hasFreeTextBuilder() {
      return freeTextBuilder != null;
    }

    /**
      * Clears the value of the 'freeText' field.
      * @return This builder.
      */
    public avro_generated_types.root_view_entity.property.Energyurbanismcharacteristic.Builder clearFreeText() {
      freeText = null;
      freeTextBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Energyurbanismcharacteristic build() {
      try {
        Energyurbanismcharacteristic record = new Energyurbanismcharacteristic();
        if (freeTextBuilder != null) {
          record.freeText = this.freeTextBuilder.build();
        } else {
          record.freeText = fieldSetFlags()[0] ? this.freeText : (avro_generated_types.root_view_entity.property.energyurbanismcharacteristic.Freetext) defaultValue(fields()[0]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Energyurbanismcharacteristic>
    WRITER$ = (org.apache.avro.io.DatumWriter<Energyurbanismcharacteristic>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Energyurbanismcharacteristic>
    READER$ = (org.apache.avro.io.DatumReader<Energyurbanismcharacteristic>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
