/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro_generated_types.root_view_entity.property.description;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Videolink extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8483302317106105840L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Videolink\",\"namespace\":\"avro_generated_types.root_view_entity.property.description\",\"fields\":[{\"name\":\"nl\",\"type\":[\"null\",\"string\"]},{\"name\":\"fr\",\"type\":[\"null\",\"string\"]},{\"name\":\"de\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence nl;
  @Deprecated public java.lang.CharSequence fr;
  @Deprecated public java.lang.CharSequence de;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Videolink() {}

  /**
   * All-args constructor.
   * @param nl The new value for nl
   * @param fr The new value for fr
   * @param de The new value for de
   */
  public Videolink(java.lang.CharSequence nl, java.lang.CharSequence fr, java.lang.CharSequence de) {
    this.nl = nl;
    this.fr = fr;
    this.de = de;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return nl;
    case 1: return fr;
    case 2: return de;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: nl = (java.lang.CharSequence)value$; break;
    case 1: fr = (java.lang.CharSequence)value$; break;
    case 2: de = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'nl' field.
   * @return The value of the 'nl' field.
   */
  public java.lang.CharSequence getNl() {
    return nl;
  }

  /**
   * Sets the value of the 'nl' field.
   * @param value the value to set.
   */
  public void setNl(java.lang.CharSequence value) {
    this.nl = value;
  }

  /**
   * Gets the value of the 'fr' field.
   * @return The value of the 'fr' field.
   */
  public java.lang.CharSequence getFr() {
    return fr;
  }

  /**
   * Sets the value of the 'fr' field.
   * @param value the value to set.
   */
  public void setFr(java.lang.CharSequence value) {
    this.fr = value;
  }

  /**
   * Gets the value of the 'de' field.
   * @return The value of the 'de' field.
   */
  public java.lang.CharSequence getDe() {
    return de;
  }

  /**
   * Sets the value of the 'de' field.
   * @param value the value to set.
   */
  public void setDe(java.lang.CharSequence value) {
    this.de = value;
  }

  /**
   * Creates a new Videolink RecordBuilder.
   * @return A new Videolink RecordBuilder
   */
  public static avro_generated_types.root_view_entity.property.description.Videolink.Builder newBuilder() {
    return new avro_generated_types.root_view_entity.property.description.Videolink.Builder();
  }

  /**
   * Creates a new Videolink RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Videolink RecordBuilder
   */
  public static avro_generated_types.root_view_entity.property.description.Videolink.Builder newBuilder(avro_generated_types.root_view_entity.property.description.Videolink.Builder other) {
    return new avro_generated_types.root_view_entity.property.description.Videolink.Builder(other);
  }

  /**
   * Creates a new Videolink RecordBuilder by copying an existing Videolink instance.
   * @param other The existing instance to copy.
   * @return A new Videolink RecordBuilder
   */
  public static avro_generated_types.root_view_entity.property.description.Videolink.Builder newBuilder(avro_generated_types.root_view_entity.property.description.Videolink other) {
    return new avro_generated_types.root_view_entity.property.description.Videolink.Builder(other);
  }

  /**
   * RecordBuilder for Videolink instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Videolink>
    implements org.apache.avro.data.RecordBuilder<Videolink> {

    private java.lang.CharSequence nl;
    private java.lang.CharSequence fr;
    private java.lang.CharSequence de;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro_generated_types.root_view_entity.property.description.Videolink.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.nl)) {
        this.nl = data().deepCopy(fields()[0].schema(), other.nl);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.fr)) {
        this.fr = data().deepCopy(fields()[1].schema(), other.fr);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.de)) {
        this.de = data().deepCopy(fields()[2].schema(), other.de);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Videolink instance
     * @param other The existing instance to copy.
     */
    private Builder(avro_generated_types.root_view_entity.property.description.Videolink other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.nl)) {
        this.nl = data().deepCopy(fields()[0].schema(), other.nl);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.fr)) {
        this.fr = data().deepCopy(fields()[1].schema(), other.fr);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.de)) {
        this.de = data().deepCopy(fields()[2].schema(), other.de);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'nl' field.
      * @return The value.
      */
    public java.lang.CharSequence getNl() {
      return nl;
    }

    /**
      * Sets the value of the 'nl' field.
      * @param value The value of 'nl'.
      * @return This builder.
      */
    public avro_generated_types.root_view_entity.property.description.Videolink.Builder setNl(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.nl = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'nl' field has been set.
      * @return True if the 'nl' field has been set, false otherwise.
      */
    public boolean hasNl() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'nl' field.
      * @return This builder.
      */
    public avro_generated_types.root_view_entity.property.description.Videolink.Builder clearNl() {
      nl = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'fr' field.
      * @return The value.
      */
    public java.lang.CharSequence getFr() {
      return fr;
    }

    /**
      * Sets the value of the 'fr' field.
      * @param value The value of 'fr'.
      * @return This builder.
      */
    public avro_generated_types.root_view_entity.property.description.Videolink.Builder setFr(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.fr = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'fr' field has been set.
      * @return True if the 'fr' field has been set, false otherwise.
      */
    public boolean hasFr() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'fr' field.
      * @return This builder.
      */
    public avro_generated_types.root_view_entity.property.description.Videolink.Builder clearFr() {
      fr = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'de' field.
      * @return The value.
      */
    public java.lang.CharSequence getDe() {
      return de;
    }

    /**
      * Sets the value of the 'de' field.
      * @param value The value of 'de'.
      * @return This builder.
      */
    public avro_generated_types.root_view_entity.property.description.Videolink.Builder setDe(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.de = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'de' field has been set.
      * @return True if the 'de' field has been set, false otherwise.
      */
    public boolean hasDe() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'de' field.
      * @return This builder.
      */
    public avro_generated_types.root_view_entity.property.description.Videolink.Builder clearDe() {
      de = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Videolink build() {
      try {
        Videolink record = new Videolink();
        record.nl = fieldSetFlags()[0] ? this.nl : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.fr = fieldSetFlags()[1] ? this.fr : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.de = fieldSetFlags()[2] ? this.de : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
